// <auto-generated />
using Fiap.Api.Donation7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation7.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260603004345_Categoria_Create_Table")]
    partial class Categoria_Create_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation7.Model.CategoriaModel", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("CategoriaId");

                    b.HasIndex("NomeCategoria")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Descricao = "Doação de alimentos não perecíveis",
                            NomeCategoria = "Alimentos"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Descricao = "Doação de roupas em bom estado",
                            NomeCategoria = "Roupas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
